name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -eux {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.10"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
    - name: Install dependencies
      run: |
        python -m pip install jupyterlab~=3.0 cookiecutter

    - name: Create pure frontend extension
      run: |
        cookiecutter . --no-input
        cd myextension
        pip install -v -e .
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "myextension.*OK"
        python -m jupyterlab.browser_check
        jupyter labextension develop . --overwrite
        pip uninstall -y myextension jupyterlab
