name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
    - name: Install dependencies
      run: |
        python -m pip install jupyterlab~=3.0 cookiecutter

    - name: Create pure frontend extension
      run: |
        cookiecutter . --no-input
        cd myextension
        pip install -e .
        jupyter labextension list 2>&1 | grep -ie "myextension.*OK"
        python -m jupyterlab.browser_check
        jlpm run install:extension
        jlpm run build

        pip uninstall -y myextension jupyterlab
